apiVersion: v1
kind: Service
metadata:
  name: order-fulfillment-service
spec:
  ports:
    - port: 8080
      name: http
    - port: 5005
      name: debug
  type: LoadBalancer
  selector:
    app: order-fulfillment-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-fulfillment-service
spec:
  selector:
    matchLabels:
      app: order-fulfillment-service
  template:
    metadata:
      labels:
        app: order-fulfillment-service
    spec:
      containers:
        - name: order-fulfillment-service
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y
          image: order-fulfillment-service
          ports:
            - containerPort: 8080
            - containerPort: 5005
